GET http://localhost:3000/actors

###

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name" : "Billy",
  "last_name" : "Zane",
  "known_for" : "Titanic"
}

###

GET http://localhost:3000/actors/31

###

PATCH http://localhost:3000/actors/31
Content-Type: application/json

{
  "first_name" : "Billy",
  "last_name" : "Zane", 
  "known_for" : "Zoolander"
}

###

DELETE http://localhost:3000/actors/36
