GET http://localhost:3000/actors.json

###

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name" : "R",
  "last_name" : "Gosling",
  "known_for" : "The Notebook",
  "gender" : "male",
  "age" : 41
}

###

GET http://localhost:3000/actors/51.json

###

PATCH http://localhost:3000/actors/31
Content-Type: application/json

{
  "first_name" : "Billy",
  "last_name" : "Zane", 
  "known_for" : "Titanic",
  "gender" : "male",
  "age" : 12
}

###

DELETE http://localhost:3000/actors/36


        ### MOVIES ###

### all movies
        
GET http://localhost:3000/movies.json

### show one movie
GET http://localhost:3000/movies/2.json

###
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title" : "Interstellar",
  "year" : "24",
  "plot" : "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  "director" : "Christopher Nolan"
}

###
PATCH http://localhost:3000/movies/13
Content-Type: application/json

{
  "title" : "This is the End",
  "year" : "2014",
  "plot" : "Six Los Angeles celebrities are stuck in James Franco's house after a series of devastating events just destroyed the city. Inside, the group not only have to face the apocalypse, but themselves",
  "director" : "Evan Goldberg, Seth Rogen"
}

###
DELETE http://localhost:3000/movies/8

### Create user
POST http://localhost:3000/users 
Content-Type: application/json

{
  "name" : "Django",
  "email" : "Django@aol.com",
  "password" : "password",
  "password_confirmation" : "password"
}